-- MySQL Script generated by MySQL Workbench
-- 03/09/15 09:11:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `forum` ;

-- -----------------------------------------------------
-- Table `forum`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`question` (
  `idquestion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` LONGTEXT NULL,
  `date` DATE NULL,
  `online` ENUM('y','n') NULL,
  `id_auteur` INT NULL,
  `objet` VARCHAR(45) NULL,
  PRIMARY KEY (`idquestion`),
  INDEX `id_auteur` (`id_auteur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum`.`reponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`reponses` (
  `idreponses` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_question` INT NULL,
  `reponse` LONGTEXT NULL,
  `id_auteur` INT NULL,
  `online` ENUM('y','n') NULL DEFAULT 'n',
  `date` DATE NULL,
  PRIMARY KEY (`idreponses`),
  INDEX `id_quatuer` (`id_auteur` ASC),
  INDEX `id_question` (`id_question` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum`.`auteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`auteurs` (
  `idauteurs` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `online` ENUM('y','n') NULL DEFAULT 'y',
  PRIMARY KEY (`idauteurs`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB;

